"""updated posts

Revision ID: 401b73b5d218
Revises: 6b8f8dcee250
Create Date: 2024-08-16 09:42:06.568632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401b73b5d218'
down_revision = '6b8f8dcee250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blog_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('content', sa.VARCHAR(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###
